// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,if:80, else:86, is:88, true:20, false:20, new:114, fn:120, let:128, def:130}
export const parser = LRParser.deserialize({
  version: 14,
  states: "0tQVQPOOO!TQPO'#C`O![QPO'#CwO!dQPO'#ClO#OQPO'#CmOOQO'#D`'#D`OOQO'#Cx'#CxOOQO'#DT'#DTO#jQPO'#CyQVQPOOOVQPO'#C^O$qQPO'#CnO$yQPO'#CsO%OQPO'#CtO%TQPO'#CuOOQO,58z,58zO%]QPO,58zO%dQPO'#CjOOQO,59R,59ROOQO,59c,59cO%kQPO,59WO%|QQO,59XO&qQPO,58{OOQO-E6w-E6wO&vQPO,58xO'OQPO,59YO'WQPO,59YO']QPO,59_O'bQPO,59`O'gQPO'#CvO'lQPO,59aOOQO1G.f1G.fOOQO,59U,59UO'qQPO,59UO!dQPO1G.sO'|QQO,59WO)uQPO1G.gO)|QPO1G.dO+sQPO'#C|O+xQPO1G.tOOQO1G.t1G.tO+xQPO1G.tOVQPO1G.yO,QQPO1G.zO,QQPO,59bO,QQPO1G.{OVQPO'#C{O,]QPO1G.pOOQO1G.p1G.pO,eQPO7+$_O,mQPO'#CbO-dQPO'#CbO.YQPO'#CqO.gQPO'#CrOOQO'#Di'#DiOVQPO'#CbO,pQPO'#CbOOQO'#Cz'#CzO.oQPO7+$ROOQO7+$R7+$RO.vQPO7+$OO!dQPO,59hOOQO-E6z-E6zOOQO7+$`7+$`O/OQPO7+$`O/WQPO7+$eO/`QPO'#CqO/nQPO7+$fO/sQPO1G.|O.yQPO7+$gO/{QPO,59gOOQO-E6y-E6yOOQO7+$[7+$[OOQO<<Gy<<GyOVQPO,58|O0WQPO,58|O0ZQPO,58|O0`QPO,59]O0hQPO,59[O0mQPO'#DOO0rQPO,59^OOQO,59^,59^O0zQPO,58|OOQO-E6x-E6xOOQO<<Gm<<GmOOQO<<Gj<<GjO2XQPO1G/SOOQO<<Gz<<GzOOQO<<HP<<HPOOQO<<HQ<<HQO2aQPO'#DPO2fQPO7+$hOOQO<<HR<<HRO2nQPO1G.hOVQPO1G.hO,QQPO'#C}O3{QPO1G.wOOQO1G.w1G.wO,QQPO1G.vO,QQPO,59jOOQO-E6|-E6|OOQO1G.x1G.xOOQO1G.h1G.hOOQO7+$n7+$nO4TQPO,59kOOQO-E6}-E6}OOQO7+$S7+$SO4YQPO7+$SOOQO,59i,59iOOQO-E6{-E6{OOQO7+$c7+$cO5gQPO7+$bO5lQPO1G/UO,QQPO1G/VOOQO<<Gn<<GnO,QQPO<<G|OOQO7+$p7+$pOOQO7+$q7+$qO5qQPOAN=hOOQOG23SG23SO#OQPO'#Cl",
  stateData: "5v~OvOS~ORTOWTOXTOYTO]SOxYOzPO}RO!TRO!ZZO!^^O!aUO!b[O!c]O~Oy_O~PVO]aO!acO~ORTOWTOXTOYTO]SO}RO!TRO!ZZO~ORTOWTOXTOYTO]SO}#lO!T#lO!ZZO~O|fORmXWmXXmXYmX]mXtmXxmXzmX}mX!TmX!ZmX!^mX!amX!bmX!cmXymX~OcjOziO~ORkO~OclO~ORmO!_jP~OyoO~PVO[pO~PVO]aO!a`a[`a!_`a_`a~O]aO!OrO!PrO!QrO!RrO!TrO!UrO!VrO!WrO!XrO!YrO~OztO~OzPO|fO~ORvOyxO~OzyO~O![zO~OV{O~OV|O~O!_}O~O[!QO_!OO|fO~O]aO!O`a!P`a!Q`a!R`a!T`a!U`a!V`a!W`a!X`a!Y`a~ORTOV!TOWTOXTOYTO]!UOc!WOz!VO}!TO!O!TO!P!TO!Q!TO!R!TO!TRO!ZZO!_!XO~Oy!]O~P(qO{!^ORQiWQiXQiYQi]QitQixQizQi|Qi}Qi!TQi!ZQi!^Qi!aQi!bQi!cQiyQi[Qi_QiVQicQi!OQi!PQi!QQi!RQi!_Qi~O![!_O~ORvOy!aO~O]!dOc!WOz!VO~O[!jO_!OO~O[!kO]aO~O]aO!_!lO~ORTOWTOXTOYTO]!UOc!WOz!VO!TRO!ZZO~O}RO!_!lO~P,uORTOWTOXTOYTO]!UOc!WOz!VO!ZZO~O}#lO!T#lO!^!pO~P-nOc!qOy!sO~Oy!vO~P(qOxYOzPO~ORvOy!yO~O|fO!a!zO~O]!dOc!WOz!VO!^!pO~O!a!{O~O_!|O!_ji~O|fO[oa_oa~O]aO!_#QO~O[#TO!`#RO~OV#UO~OV#VO~Oc!qOy#XO~O_#YO|fORUaVUaWUaXUaYUa]UacUayUazUa}Ua!OUa!PUa!QUa!RUa!TUa!ZUa!_Ua~O]aO_#ZO~OR#[O~O_!|O!_jq~O_#^O|fORUiVUiWUiXUiYUi]UicUiyUizUi}Ui!OUi!PUi!QUi!RUi!TUi!ZUi!_Ui~O[#bO!`#RO~OV#eO~O_#fO|fORUqVUqWUqXUqYUq]UqcUqyUqzUq}Uq!OUq!PUq!QUq!RUq!TUq!ZUq!_Uq~O!_#gO~O_#hO~O[#kO~O",
  goto: "'v!^PP!_P!o#V#dPPPP#hPP$OP#h#h#hP$Y$Y$Y#V#V#V$i#V#V$l$v$|%S%^%d%jPPP%pPPPPPPPPPP&]PPPPPPPP'RfVOPXY`az!O!X!l#QR!w!^fVOPXY`az!O!X!l#QQuhQ!w!^R#O!ggVOPXY`az!O!X!l#QT!Zt![yTOPRSXY`artz!O!T!U!X![!_!l#Q#labQdes!R!S!m!xk!Wt{|}!T!U![!d#R#U#V#e#gRn^QXOQ`PTgX`Q![tR!u![Q!PqR!i!PQwiS!`w!bR!byQ#S!oR#a#SQ!r!VR#W!rQ!}!fR#]!}WWOPX`QhYQqaQ!czQ!h!OQ!t!XQ#P!lR#_#QfQOPXY`az!O!X!l#QQdRSeS!UQs#lQ!RrS!St![Q!m!TR!x!_S!Yt![Q!e{Q!f|Q!g}Q!n!TS!o!U!dQ#`#RQ#c#UQ#d#VQ#i#eR#j#g",
  nodeNames: "⚠ Program If Identifier Block Is Match Dot Number String Boolean Call ) ( ArgList Comma Unary Binary ObjInit TypeIdentifier Func Or Obj Let Def Fn ParamList Expr Empty",
  maxTerm: 65,
  nodeProps: [
    ["group", -8,2,4,5,23,24,25,27,28,"Statement",-8,3,8,9,10,11,16,17,18,"Expression",-4,19,20,21,22,"Type"],
    ["openedBy", 12,"("],
    ["closedBy", 13,")"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 7,
  tokenData: "(u~RnX^#Ppq#Pqr#trs$Rxy%oyz%tz{%y{|&O}!O&T!P!Q&b!Q![&g![!]&o!]!^&t!^!_&y!_!`'W!`!a'e!c!}'r#R#S(T#T#o(T#o#p(f#p#q(k#q#r(p#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#UYv~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#PR#yP}P!_!`#|Q$RO!YQ~$UVOr$Rrs$ks#O$R#O#P$p#P;'S$R;'S;=`%i<%lO$R~$pOX~~$sRO;'S$R;'S;=`$|;=`O$R~%PWOr$Rrs$ks#O$R#O#P$p#P;'S$R;'S;=`%i;=`<%l$R<%lO$R~%lP;=`<%l$R~%tO]~~%yO[~~&OO!V~~&TO!U~~&YP!T~!`!a&]~&bO!_~~&gO!W~~&lPW~!Q![&g~&tOV~~&yO!a~~'OP!R~!_!`'R~'WO!Q~R']P![P!_!`'`Q'eO!XQ~'jP!P~!_!`'m~'rO!O~~'wSc~!Q!['r!c!}'r#R#S'r#T#o'r~(YSR~!Q![(T!c!}(T#R#S(T#T#o(T~(kOz~~(pO!`~~(uOy~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
