name: Build and Deploy

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Compile WASM
              id: compile
              uses: rust-build/rust-build.action@v1.4.4
              with:
                  RUSTTARGET: wasm32-wasi
                  UPLOAD_MODE: none
            - uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
            - name: Build Website
              working-directory: ./web
              run: npm ci && npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: web/dist
